pr:
- master

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'rm -rf *IntegrationTests'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    testRunTitle: 'PR_RunTests'
