pr:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker run --name db -d -e MYSQL_ROOT_PASSWORD=$DB_PSW_PASSWORD -e MYSQL_DATABASE=test -p 3306:3306 -p 33060:33060 mysql
  displayName: Run DB container

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $PSW_SMPT_HOST_SERVER
      echo $PSW_EMAIL_USERNAME
      echo $PSW_SMTP_SSL_PORT
      sleep 10
  displayName: Wait for DB startup

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*IntegrationTests/*.csproj'
    testRunTitle: 'PR_RunIntegrationTests'
  displayName: RUN Integration Tests
