pr:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: UseDotNet@2
  displayName: '.NET Core SDK 3.1.200'
  inputs:
    packageType: 'sdk'
    version: '3.1.200'
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
  displayName: Build solution
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*UnitTests/*.csproj'
    testRunTitle: 'PR_RunUnitTests'
  displayName: Unit Tests
