version: "3.8"

services:
  mysql:
   build:
     dockerfile: /db/Dockerfile
   container_name: db
   networks:
     - network
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: test
   ports:
     - 3306:3306
     - 33060:33060
  userApi:
    build:
      dockerfile: Dockerfile
    container_name: userApi
    restart: on-failure
    networks:
      - network
    ports:
      - 5003:80
    env_file:
      - secrets.env
    depends_on:
      -mysql

  nginx:
    build:
      context: ../../HospitalFrontend
      dockerfile: FrontDockerfile
    container_name: front
    environment:
      PORT: 80
    networks:
      - network
    ports:
      - 8080:80
    restart: always


networks:
  network:
    name: network
    driver: bridge
