pr: none

# pipeline is an expansion of CI, and is triggered as such

pool:
  vmImage: 'ubuntu-16.04'



steps:
- task: DownloadBuildArtifacts@0
  displayName: 'Download CI Build Artifacts'
  inputs:
    buildType: 'specific'
    project: 'b1b2ce57-5a6f-427b-8869-dc3414677299'
    pipeline: '10'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    downloadPath: '$(System.ArtifactsDirectory)'


- task: Docker@2
  displayName: 'Docker build pswaspnet feedback'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'build'
    Dockerfile: 'DevOps/docker/AspNetDockerfile'
    buildContext: '$(System.ArtifactsDirectory)/dropfeedback'
    tags: 'feedback'
    addPipelineData: false

- task: Docker@2
  displayName: 'Docker build pswaspnet hospital'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'build'
    Dockerfile: 'DevOps/docker/AspNetDockerfile'
    buildContext: '$(System.ArtifactsDirectory)/drophospital'
    tags: 'hospital'
    addPipelineData: false

- task: Docker@2
  displayName: 'Docker build pswaspnet schedule'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'build'
    Dockerfile: 'DevOps/docker/AspNetDockerfile'
    buildContext: '$(System.ArtifactsDirectory)/dropschedule'
    tags: 'schedule'
    addPipelineData: false

- task: Docker@2
  displayName: 'Docker build pswaspnet user'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'build'
    Dockerfile: 'DevOps/docker/AspNetDockerfile'
    buildContext: '$(System.ArtifactsDirectory)/dropuser'
    tags: 'user'
    addPipelineData: false

- task: Docker@2
  displayName: 'Docker build pswaspnet ocelot'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'build'
    Dockerfile: 'DevOps/docker/AspNetDockerfile'
    buildContext: '$(System.ArtifactsDirectory)/dropocelot'
    tags: 'ocelot'
    addPipelineData: false

- task: Docker@2
  displayName: 'Docker build pswaspnet event store'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'build'
    Dockerfile: 'DevOps/docker/AspNetDockerfile'
    buildContext: '$(System.ArtifactsDirectory)/dropes'
    tags: 'es'
    addPipelineData: false


- task: Docker@2
  displayName: 'Docker push pswaspnet feedback'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'push'
    tags: 'feedback'
    addPipelineData: false

- task: Docker@2
  displayName: 'Docker push pswaspnet hospital'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'push'
    tags: 'hospital'
    addPipelineData: false

- task: Docker@2
  displayName: 'Docker push pswaspnet schedule'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'push'
    tags: 'schedule'
    addPipelineData: false

- task: Docker@2
  displayName: 'Docker push pswaspnet user'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'push'
    tags: 'user'
    addPipelineData: false

- task: Docker@2
  displayName: 'Docker push pswaspnet ocelot'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'push'
    tags: 'ocelot'
    addPipelineData: false

- task: Docker@2
  displayName: 'Docker push pswaspnet event store'
  inputs:
    containerRegistry: 'psw'
    repository: 'fmaster/pswaspnet'
    command: 'push'
    tags: 'es'
    addPipelineData: false
