trigger: none
pr: none

schedules:
- cron: "0 * * * *"
  displayName: Git Tree logging to track changes in history (provide commit backdating detection possibilities)
  branches:
    exclude:
      - 
  always: true

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git checkout master
      git --no-pager log --graph --all --source --full-history #--since=2.weeks
    workingDirectory: '$(Agent.BuildDirectory)/s'